package com.returnflow.pdf;

import java.time.Instant;

/**
 * Everything the administrative PDF renders, already read from the
 * authoritative persisted return by the caller. Deliberately built from
 * presentation-neutral primitives (already-resolved display labels, plain
 * {@link Instant}s, raw signature SVG bytes) rather than domain enums or the
 * {@code ReturnRecord} entity, so this module stays free of any dependency on
 * {@code returnrecord} — the dependency runs one way only, from the return
 * domain to this renderer.
 *
 * <p>No value here ever originates from a client request body: the PDF
 * endpoint receives only a return identifier, and every field below is loaded
 * from the database (root {@code CLAUDE.md} §18 — "generated by the backend
 * from trusted database data").
 *
 * <p>Photos are deliberately absent: they are excluded from the PDF (root
 * {@code CLAUDE.md} §14/§18), so they are never even loaded.
 *
 * <p>Nullable fields are exactly those the domain allows to be absent
 * ({@code reasonDetails}, {@code driverObservation}, {@code routeName},
 * {@code warehouseObservation}, {@code reviewStartedAt}, and the actor names,
 * which resolve to {@code null} for a since-removed account).
 */
public record ReturnPdfDocument(
		String returnNumber,
		String status,
		String customerName,
		String productName,
		int quantity,
		String unit,
		String reason,
		String reasonDetails,
		String driverObservation,
		String driverName,
		String routeCode,
		String routeName,
		Instant createdAt,
		Instant reviewStartedAt,
		Instant closedAt,
		Boolean sellable,
		Boolean creditCustomer,
		Boolean chargeCustomer,
		Boolean chargeDriver,
		String warehouseObservation,
		String warehouseRepresentativeName,
		String reviewedByName,
		String closedByName,
		String customerRepresentativeName,
		Instant customerSignedAt,
		byte[] customerSignatureSvg,
		byte[] warehouseSignatureSvg) {
}
